
version: 2

models:
  - name: matches
    description: "ATP tennis matches schema"
    columns:
      - name: tourney_id
        description: "The ID of the tournament."
        data_tests:
          - not_null
      - name: winner_id
        description: "The ID of the winning player."
        data_tests:
          - not_null
      - name: loser_id
        description: "The ID of the losing player."
        data_tests:
          - not_null
      - name: surface
        description: "The surface of the court."
        data_tests:
          - accepted_values:
              values: ['Grass', 'Hard', 'Clay']
